name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'  # Enable pip caching

    - name: Set cache directory
      run: |
        # Set a custom cache directory that the runner can access
        mkdir -p $HOME/.cache/pip
        export PIP_CACHE_DIR=$HOME/.cache/pip
        echo "PIP_CACHE_DIR=${PIP_CACHE_DIR}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --cache-dir $PIP_CACHE_DIR

    - name: Run tests
      run: |
        pytest test_app.py

