name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install dependencies (pytest for tests)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Run tests with pytest
    - name: Run tests
      run: |
        pytest test_app.py

